#!/bin/bash
# Example of setting the TPS variable in the jndi.properties file
# If it is available it is better to use the tool web pages or curl
if [ "$1" ]; then
    TPS=$1
    if ! [ "$TPS" -eq "$TPS" ] 2>/dev/null; then
        echo not a number
        exit 1
    fi
else
    TPS=1
fi
FILE=jndi.properties
if cat $FILE | sed "s/TPS=.*/TPS=$TPS/g" > $FILE.tmp
then
    mv $FILE.tmp $FILE
fi
